### ISSUE TITLE
printout of web-lit activities 

### ISSUE THREAD

**Issue by anmechung** [mozilla/web-lit-core#16]
@gvn is there an relatively easy way to print out web lit activities from GitHub?  Thinking of educators who may want to do this.  I tried printing from browser and it will only print out  up to where description begins.

**Comment by gvn** [comment]
This is going to be tricky to debug. I will say that the print preview in Chrome included all pages of the activity I tried to print while Firefox did not. This may be a browser bug of some kind.

Since this is a bit of an edge case I would suggest using Chrome to print if necessary in the meantime.

If we can't figure out what's causing this, we could put in a basic print stylesheet that might take care of things.

How high of a priority is this? (CC: @alanmoo )

**Comment by anmechung** [comment]
@gvn  IMO, not a priority as long I can add info on how they can print in Chrome. Thanks for looking into it!
